# Changelog {.unnumbered}

## 0.13.0 – 2025-06-29

### Added

- works: TumW D.2.22
- incipits and metadata: TumW A.22 and C.2.4
- sources:
  - A-Wn: Mus.Hs.17332
  - A-Wst: MH-9464, MH-9465, MH-9466, MH-9467, and MH-10575
- editions: Fuerlinger 1997 and Schmid 1900b
- work numbers from MacIntyre 1984
- a link to the poster presented at the IAML 2025 Conference

### Changed

- technically equivalent to WerW v0.15.0


## 0.12.0 – 2025-05-25

### Added

- works: TumW A.L15, E.5.1/2/6, and G.L11
- incipits and metadata: TumW D.2.11/12, D.3.3, D.4.4, E.1.2, E.2.5/6, E.5.7, F.6, G.16, I.9, and J.17
- sources
  - A-KR H 50/175
  - A-Sd A 854
  - A-Wdtö scores
  - CZ-Pnm XLIX F 146
  - D-B Mus.ms. 9101/2 (3)
  - D-Mbs Mus.ms. 5520
  - D-MT Mus.ms. 1738
  - H-Bn Ms. mus. IV. 1.907
  - H-Sp, Vpl, a) 19
  - I-Rama A-Mss-523
  - PL-KŁwnm M-67
  - PL-Wu RM 5158 and RM 5186
- reference MelkInv and many modern editions
- acknowledgements for CZ-KRA/CZ-UO
- A-Wst sources to be catalogued
- a siglum A-Wdtö for sources in the archive of the Denkmäler der Tonkunst in Österreich
- an appendix “Prints” that contains a table with all known modern editions
- links to the Klostermusiksammlungen database for A-GÖ, A-M, and A-KN sources
- TumW C.3.12: alternative title from A-Wgm source
- TumW H.2: details on A-Ws source
- TumW L.1: info that single known source A-Wn Mus.Hs.24412 is currently undiscoverable
- TumW L.4: info that single known source in CZ-KRA/CZ-UO is currently undiscoverable

### Changed

- Group E has been renamed (again) to “Marian antiphons”.
- In subgroup E.2, the following works have been renumbered: 1 → 8, 2 → 6, 3 → 2, 4 → 1, 5 → 4, 6 → 7, 7 → 5, and 8 → 3.
- TumW E.5.1–3/4–6 have been renumbered to E.5.7–9/3–5.
- updated the favicon and title block banner background
- technically equivalent to WerW v0.14.0

### Fixed

- Source A-Ws E 3/25 has been correctly assigned to TumW A.18 (instead of TumW A.39).


## 0.11.0 – 2025-04-19

### Added

- works: TumW D.2.12 and L.4
- incipits and metadata: TumW A.12, C.2.3, C.3.16, C.4.3, C.5.S1, and D.2.5
- source D-OB MO 812 for TumW C.3.14
- reference Pulkert 1973

### Changed

- Subgroup D.4 has been renamed to *Canticles*.
- TumW D.2.21 has been reclassified to D.4.4.
- In group D.2, works 12–20 have been renumbered to 13–21.
- technically equivalent to WerW v0.13.0


## 0.10.0 – 2025-03-08

### Added

- works: TumW C.3.27/28 and J.L10
- incipits and metadata: TumW A.38, C.1.2, C.2.2, C.3.14, C.4.2, C.5.29, C.6.2, D.2.13, D.4.3, E.1.1, E.2.1, E.4.1, E.5.6, G.5, I.17/18, J.15, and L.3
- sources:
  - A-Wgm: I 24380
  - D-Bsa: SA 3541 (7)
  - SK-BRm: box 526, inv.no. 3222
- acknowledgements for CZ-KLm, CZ-Nlob, SK-BRm, and Perutková
- references Blume 1992, Horvath 1971, Kellner 1956, Kim 1998, and Pfiffig 1975
- a section describing works not yet catalogued
- methods now mention the number of works in RISM that have been included
- TumW A.54: shelfmark in CZ-KLm
- TumW A.S10: shelfmark in A-KR 
- TumW D.1.4: details on A-KR sources
- Klosterneuburg inventory C
- a table with Klosterneuburg inventories as appendix

### Changed

- Subgroup C.6 has been renamed to *Miscellaneous*.
- TumW F.9 has been reclassified to C.6.2.
- TumW C.3.L6 has been merged to 28; thus, TumW C.3.L7–11 have been renumbered to L6–10.
- The library siglum CZ-LIT has been replaced by CZ-Nlob, since the sources have been moved.
- In group G, the following works have been renumbered: 16 → 1, 11 → 2, 14 → 3, 18 → 4, 9 → 5, 19 → 7, 15 → 8, 5 → 9, 1 → 10, 8 → 11, 10 → 12, 12 → 13, 17 → 14, 20 → 15, 21 → 16, 7 → 17, 2 → 18, 3 → 19, 4 → 20, and 13 → 21.
- technically equivalent to WerW v0.12.0


## 0.9.0 – 2025-01-18

### Added

- works: TumW C.3.23–26, D.2.4, E.4.3, and I.23–27
- incipits: TumW C.3.3, D.1.2 (Lauda Jerusalem), and D.3.1
- metadata: TumW C.3.3 and D.3.1
- sources:
  - A-Ws
  - H-Gk (details in metadata of TumW D.3.7)
  - CZ-K 273 K I
- acknowledgements for A-Ws and H-Gk
- reference Freeman 1971
- concordances of previous catalogues to TumW in the appendix

### Changed

- TumW D.2.4–20 have been renumbered to D.2.5–21.
- technically equivalent to WerW v0.11.0


## 0.8.0 – 2024-12-16

### Added

- works: TumW C.3.L3–11, C.4.L2+3, C.5.S1, C.6.1, D.1.L2, D.2.L1/2, D.3.L1/2, D.4.L1+2, E.4.L1/2, E.5.1–6, G.L2–12, I.L3–5, J.L4–9, and K.L6–8
- incipits for TumW A.35, C.2.1, C.4.5, C.5.S1, C.6.1, E.5.5, H.2, and J.19
- metadata for TumW A.17/27/35, C.2.1/5–7, C.3.1/2/4–13/15/17/18/20, C.4.5, D.2.5-8/17, D.3.6, E.2.8, E.4.2, E.5.5, F.1–3, G.7/18, H.1/2, I.1/4/6-8/13/15/16, J.6/13/14, and K.2/9
- sources:
  - A-H inventories
  - A-KN
  - CZ-K
  - TumW F.2: I-Rsc A-Ms 523
  - TumW G.14: CZ-Pak 1518
  - TumW I.11: A-M V/1438
- references: Armstrong 1993, 2004, Bardos 1980, Czernin 1995, Esterházy inventory 1812/13, Fischer 1912, Herzogenburg inventories A and B, Hornbacher 2023, Klosterneuburg inventories A, B, and E, Radant 1982, Preisl 2022, Schmid 1901, and Tichý 2019
- subgroups: *D.5 Introits* and *F.5 Sub tuum praesidium*
- an appendix *Inventories*, which contains tables describing the Herzogenburg inventories
- acknowledgements for A-H, A-KN, A-MB, A-Wgm, CZ-Bu, D-OB, H-KE, H-PH, Hilscher, Gasche, and Tichý

### Changed

- TumW A.3 has been reclassified as A.S10. Thus, TumW A.4–57 have been renumbered to 3–56.
- TumW C.2.2 has been merged to C.3.12. Thus, TumW C.2.3–9 have been renamed to C.2.2–8.
- Subgroup D.2 has been completely revised, including several renumberings.
- Group E has been renumbered to subgroup C.5. Thus, former subgroup C.5 has been renumbered to C.6, and groups F–M are now groups E–L.
- Group E (formerly F) has been renamed to “Marian hymns”.
- In group G (formerly H), the following entries have been renumbered: L9 → 20, L11 → 21, L8 → 22, L10 → L8, and L12 → L9. Moreover, TumW G.16 has been merged to G.14. Thus, TumW G.17–20 have been renamed to G.16–19.
- technically equivalent to WerW v0.10.0

### Removed

- “Wondratsch” prefixes of all A-GÖ signatures


## 0.7.0 – 2024-10-12

### Added

- works: TumW A.55–57/L12–14, C.3.L1/2, C.4./L1, D.1.S1, D.2.S1, F.1.6/7, F.3.L1/2, H.L1, I.4, K.21/L1-3, L.L2–5H.1/8/16, and I.3
- incipits for TumW A.10/12, D.1.4, and G.5
- metadata for TumW A.10/12, D.1.4, and G.5
- short incipits for TumW A.55-57/L12-14, C.3.L1/2, C.4.L1, F.1.6/7, F.3.L1/2, H.1/8/16/L1, I.3, K.21/L1-3, and L.L2-5
- references: Ball 1900, Bartos 2013, Bartos 2018, Brown 1996, Brtnice Inventory, Eybl 2011, Freeman 1992, Haberkamp 1986, MacIntyre 1984, Oppova 2013, Rajhrad Inventory A and B, Rampackova 2009, Sanders 1973, Schröder 1991, Slavicky 2004, Strakova 1963, 1965, Tichy 2014, and Tichy 2014b
- sources:
  - A-SEI: E XV 2 a IV (1) and (2), E XVII 1 c I and II, E XXII 9 a, b and c
  - H-P: C 25
- acknowledgements for A-SEI, A-WIL, A-Wps, and H-P

### Changed

- Within subgroup D.2, the following works have been renumbered: 3 → 11, 4/5 → 3/4, 6 → 9, 7 → 18, 8–11 → 5–8, 12 → 10, and 13–18 → 12–17.
- Subgroup F.3 has been renumbered to F.4, since two (lost) *Regina coeli* have been added.
- technically equivalent to WerW v0.9.0


## 0.6.0 – 2024-09-14

### Added

- incipits for TumW D.3.8
- metadata for TumW D.3.7/8
- manual incipits for almost all works, since many incipits were previously missing in the catalogue
- a new subgroup for Misereres (D.3)
- reference Eybl 1996
- acknowledgements for A-GÖ
- information on the currently undiscoverable A-HE source for TumW H.19

### Changed

- Incipits for almost all sources (copies by Schmid) in D-Dl are now available. Thus, the sources previously summarized in TumW I.S1 and M.S2 could be assigned to their respective works.
- Many works have been renumbered, reclassified, split, merged, or removed, as summarized in the following table (renumbering is not explicitly annotated).

::: {.callout-note title="Details" collapse="true"}

|old|new|notes|
|-|-|-|
|A.43|A.10|merged|
|A.44|A.43||
|A.45|A.44||
|A.46|A.45||
|A.47|A.46||
|A.48|A.47||
|A.49|A.15|merged|
|A.50|A.S8||
|A.51|A.S9||
|A.52|A.48||
|A.53|A.49||
|A.54|A.50||
|A.55|A.51||
|A.56|A.52||
|A.57|A.53||
|A.58|A.54||
|A.59|–|removed|
|A.60|–|removed|
|A.61|–|removed|
|A.62|–|removed|
|C.3.21|C.4.8||
|C.3.22|C.3.21||
|D.2.11|D.2.3|merged|
|D.2.5|D.2.5 to 7|split|
|D.2.6|D.2.8||
|D.2.7|D.2.9||
|D.2.8|D.2.10||
|D.2.9|D.2.11||
|D.2.10|D.2.12||
|D.2.12|D.2.13||
|D.2.13|D.2.14||
|D.2.14|D.2.15||
|D.2.15|D.2.16||
|D.2.16|D.2.17||
|D.2.17|D.3.1|new subgroup|
|D.2.18|D.3.2||
|D.2.19|D.3.3||
|D.2.20|D.3.4||
|D.2.21|D.3.5||
|D.2.22|D.3.6||
|D.2.23|D.3.7||
|D.2.24|D.3.8||
|D.2.25|D.3.9||
|D.2.26|D.2.18||
|D.3.x|D.4.x||
|E.30|C.3.22||
|F.1.6|–|removed|
|H.21|H.S1||
|J.17|J.19||
|J.18|J.20||
|K.16|J.17/18|split|
|K.17|K.16||
|K.18|K.17||
|K.19|K.18||
|K.20|K.19||
|K.21|K.S1||
|K.22|K.20||
|M.3|M.2||
|M.4|J.21||
|M.5|M.3||
|M.6|J.22||

:::

- Group D has been renamed (Vespers → Vespers and psalms).
- technically equivalent to WerW v0.8.0

### Removed

- the catalogue in ODS format with incipits (`data/catalogue_works.ods`)


## 0.5.0 – 2024-08-09

### Added

- incipits for TumW C.3.2 and H.7
- The catalogue now also comprises spurious and lost works (with incipits where known).
- Reference columns in the catalogue have been renamed: KliCh (Klinka), ReiMa (Reichert), PesMa (Peschek), and VogIn (Vogg).
- references: Haberkamp 1993, Harich 1975, Kiesewetter 1847, Mitterschiffthaler 1997, Opatrny 2012, Sherman 2001, Štefan 1985, and St Peter Inventory

### Changed

- The bibliography now appears on a separate page.
- technically equivalent to WerW v0.7.0

### Removed

- subgroups of masses (group A)


## 0.4.0 – 2024-07-13

### Added

- manual incipits for TumW B.1 (Sequentia to Agnus Dei)
- MEI metadata for TumW B.1
- details on differences between the guidelines and those of WerW

### Changed

- technically equivalent to WerW v0.6.0


## 0.3.0 – 2024-06-30

### Added

- manual incipits for TumW C.3.5/10/15
- works in CZ-Pn

### Changed

- technically equivalent to WerW v0.5.0


## 0.2.0 – 2024-06-16

### Added

- manual incipits for TumW A.3.4/14, B.1, C.2.6–8, C.3.7–9/11–13/17/18/20, D.1.4, D.2.6–9/16/22/23, F.2.8, F.3.2, G.1–3, H.19, I.1, J.1/4/6–8/13/15/16, K.6/9/10/13/14, and L.2/9

### Changed

- technically equivalent to WerW v0.4.0


## 0.1.0 – 2024-05-31

### Added

- initial release
