---
title-block-banner: true
---

# Introduction {.unnumbered}

This website contains an evolving thematic catalogue of František Ignác Antonín Tůma's works.

::: {.callout-important}
## Caution

This catalogue is **work-in-progress** and likely contains errors or duplicate entries. Its contents are subject to change as we screen more and more manuscripts.
:::

For general and biographical information on Werner, see @Postolka2001 and @Slavicky2006.


## Overview

We classify Tůma's works as *Vocal music* (groups A to I) and *instrumental music* (groups J to M); moreover, an appendix contains spurious and uncertain attributions (group Z). Groups A, C, D, and F are further divided into subgroups to provide a more fine-grained classification and to preserve work numbering if further works are discovered. The catalogue also cites lost works whose existence has been sufficiently proven.

**Vocal music** comprises

- *A. Masses*<br/>
  (1) pure a capella style<br/>
  (2) free a capella style<br/>
  (3) modern style<br/>
  (4) lost works<br/>
  (5) spurious works
- *B. Requiems*
- *C. Short liturgical works*<br/>
  (1) Graduals<br/>
  (2) Hymns<br/>
  (3) Motets<br/>
  (4) Offertories
- *D. Vespers*<br/>
  (1) Complete vespers<br/>
  (2) Psalms<br/>
  (3) Magnificats
- *E. Responsories*
- *F. Marian antiphons*<br/>
  (1) Alma redemptoris mater<br/>
  (2) Ave regina coelorum<br/>
  (3) Salve regina
- *G. Sequences*
- *H. Litanies*
- *I. Miscellaneous vocal works*

**Instrumental music** comprises

- *J. Sonatas*
- *K. Sinfonias*
- *L. Partitas*
- *M. Miscellaneous instrumental works*

Currently, the catalogue contains the following information for each work:

- title
- sources (linked to the respective RISM entry), and
- one preliminary incipit (i.e., the first incipit of the first source with RISM entry).

For an increasing number of works, detailed metadata in MEI format [@MEI2023] is available.

Works in the catalogue should be cited by the abbreviation “TumW”, followed by the group, subgroup (if applicable), and work number; the latter three components should be separated by a period.


## Methods

### Sources

We consulted the following sources, of which some contain partial catalogues of Werner's works:

- @Vogg1951 – works known around 1950
- @Peschek1956 – masses known in the 1950s
- @Klinka1975 – vocal works, including practical editions of several motets
- @Eitner1903 – sources known around 1900
- @Riedel1979 – works in the Göttweig Abbey archive

### Analysis

The work list assembled from these sources (`data/catalogue_works.csv`) was checked against and supplemented by RISM entries. To this end, entries were downloaded via [*sru-downloader*](https://github.com/rism-international/sru-downloader) on 2024-05-26, yielding 309 entries. In the resulting XML file, all tags in the `zs` namespace were removed, yielding the XML file `data/rism_entries.xml`, which only contains [MarcXML](https://www.loc.gov/standards/marcxml/) tags:

```bash
java -jar SRUDownloader.jar "https://muscat.rism.info/sru/sources?operation=searchRetrieve&version=1.1&query=creator=%22T%C5%AFma,+Franti%C5%A1ek+Ign%C3%A1c%22&maximumRecords=100"
grep -v "<zs:" output.xml | \
  grep -v "</zs:" | \
  grep -v "<marc:collection" | \
  grep -v "</marc:collection" | \
  sed '1 a\<marc:collection xmlns:marc="http://www.loc.gov/MARC21/slim">' | \
  sed '$ a\</marc:collection>' \
  > rism_entries.xml
rm output.xml
```
From this file, searchable HTML tables were created via `script/parse_rism_search_results.py` and `make_rism_tables.R` and stored in `data_generated/rism_tables/`.

Pages for all groups of works were generated automatically from `catalogue_overview.csv` and `catalogue_works.csv`. If manually curated incipits were unavailable for a work, the first incipit of the first source with a RISM entry was included. Data from the [RISM Catalogue](https://opac.rism.info) (e.g., Plaine & Easie Code for incipits) by the *Répertoire International des Sources Musicales* is licensed under a Creative Commons Attribution CC-BY 3.0 Unported License.

Detailed work metadata was edited with [MerMEId v2.0](https://mermeid.edirom.de/). Incipits were either prepared with [MuseScore](https://musescore.org), polished with [mei-friend](https://mei-friend.mdw.ac.at), and rendered with [Verovio](https://www.verovio.org), or created with [LilyPond](https://lilypond.org/) and [EES Tools](https://github.com/edition-esser-skala/ees-tools). HTML and XML files were exported from MerMEId and post-processed. These pages are rendered using the [BravuraText](https://github.com/steinbergmedia/bravura) font v1.392 and Verovio.


### Data and code availability

Datasets and code used for preparing this catalogue are available from [GitHub](https://github.com/edition-esser-skala/tuma-catalogue-of-works).


## Acknowledgements

Assistance of the following people and institutions is gratefully acknowledged:
Thomas Dolezal (Dommusikarchiv Eisenstadt – A-Ed),
P. Altman Pötsch (Benediktinerstift Kremsmünster, Regenterei und Musikarchiv – A-KR),
Peter Deinhammer (Benediktinerstift Lambach, Musikarchiv – A-LA),
Christian Schüller (Röm.-Kath. Pfarramt Maria Taferl – A-MT),
Ludmila Šmídová (Národní knihovna České republiky, Praha – CZ-Pu),
Sebastian Lindblom (Musik- och teaterbiblioteket, Stockholm – S-Skma),
as well as the staff of
the Österreichische Nationalbibliothek, Musiksammlung, Wien (A-Wn),
the Staatsbibliothek zu Berlin - Preußischer Kulturbesitz, Musikabteilung (D-B),
the Universität der Künste Berlin, Universitätsbibliothek, Berlin (D-Bhm)
the Sächsische Landesbibliothek - Staats- und Universitätsbibliothek, Dresden (D-Dl),
the Badische Landesbibliothek, Musiksammlung, Karlsruhe (D-KA),
and the Universitetsbiblioteket Lund (S-L).


## References

::: {#refs}
:::


## Contact

Do you work on a similar catalogue? Would like to team up or support the project? Feel free to reach out to me via [email](mailto:wolfgang@esser-skala.at)!

Disclosure (§25 Mediengesetz)
: This website is privately provided and maintained by Wolfgang Esser-Skala, Wolfgangseestraße 31g, 5023 Koppl.
